version: '3'
services:
  product-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_ID}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_DATABASE=product
      - MYSQL_TCP_PORT=13306
    ports:
      - 13306:13306
    volumes:
      - mysqldata_product:/var/lib/mysql
    networks:
      - msa-project-02
  review-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_ID}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_DATABASE=review
      - MYSQL_TCP_PORT=23306
    ports:
      - 23306:23306
    volumes:
      - mysqldata_review:/var/lib/mysql
    networks:
      - msa-project-02
  config-server:
    image: sheepbomb/configserver:latest
    restart: always
    ports:
      - 8888:8888
    networks:
      - msa-project-02
    environment:
      - SPRING_PROFILE:default
  discovery-server:
    image: sheepbomb/discoveryserver:latest
    restart: always
    ports:
      - 8761:8761
    networks:
      - msa-project-02
    environment:
      - CONFIG_SERVER=config-server:8888
      - SPRING_PROFILE:default
    depends_on:
      - config-server
  gateway-server:
    image: sheepbomb/apigateway:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - msa-project-02
    environment:
      - CONFIG_SERVER=config-server:8888
      - DISCOVERY_SERVER=discovery-server:8761
      - SPRING_PROFILE:default
    depends_on:
      - config-server
      - discovery-server
  product-service:
    image: sheepbomb/product:latest
    restart: always
    networks:
      - msa-project-02
    environment:
      - CONFIG_SERVER=config-server:8888
      - DISCOVERY_SERVER=discovery-server:8761
      - MYSQL_HOST=product-db
      - MYSQL_USER=${MYSQL_ID}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - SPRING_PROFILE:default
    depends_on:
      - config-server
      - discovery-server
      - gateway-server
      - product-db
  review-service:
    image: sheepbomb/review:latest
    restart: always
    networks:
      - msa-project-02
    environment:
      - CONFIG_SERVER=config-server:8888
      - DISCOVERY_SERVER=discovery-server:8761
      - MYSQL_HOST=review-db
      - MYSQL_USER=${MYSQL_ID}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - SPRING_PROFILE:default
    depends_on:
      - config-server
      - discovery-server
      - gateway-server
      - review-db
volumes:
  mysqldata_product:
  mysqldata_review:
networks:
  msa-project-02:
    driver: bridge
